import React from 'react';
import {throttle} from 'lodash';

import AceEditor from 'react-ace';
let brace = require('brace');
require('brace/mode/javascript');
require('brace/theme/solarized_dark');

/* Interface between React and Ace Editor:
   React may pass in staticCodeExample and cause component
   to re-render entirely, but the
   subscriptions to code updating via the CodeStore/SequencerStore
   change the underlying Ace Editor state directly and 
   so don't trigger React re-rendering */
import SequencerStore from '../../../../../modules/stores/SequencerStore.js';
import CodeStore from '../../../../../modules/stores/CodeStore.js';
import LiveOptionStore from '../../../../../modules/stores/LiveOptionStore.js';

class Editor {

  static propTypes = {
    staticCodeExample: React.PropTypes.func,
    options: React.PropTypes.object,
  }

  static defaultProps = {
    options: {
      theme: 'solarized_dark',
      mode: 'javascript',
      height: '800px',
      width: '100%',
      fontSize: 18,
      cursorStart: 1,
      editorProps: {
        $blockScrolling: Infinity,
        readOnly: false,
      },
    },
  }

  componentDidMount = () => {
    SequencerStore.subscribeEditor(this.onSequencerActionUpdate);
    LiveOptionStore.subscribeListener(this.onPlayPauseUpdate);
  }

  componentWillUnmount = () => {
    SequencerStore.unsubscribeEditor(this.onSequencerActionUpdate);
    LiveOptionStore.unsubscribeListener(this.onPlayPauseUpdate);
  }

  onSequencerActionUpdate = () => {
    let editor = this.refs.aceEditor.editor;
    // action happened, disable editing and select range result
    if (LiveOptionStore.isCodeRunning()) {
      editor.setReadOnly(true);
      let execCodeBlock = SequencerStore.getEditorOutput().execCodeBlock;
      /* try to find via regex first, since the way AceEditor displays
         tabs means that selections include the preceding tab so don't 
         look as nice. */
      let range = editor.find(execCodeBlock);
      if (!range) {
        /* backup selection due to potential of escodegen not rebuilding
           the exact same code string */
        range = SequencerStore.getEditorOutput().range; // .collapseRows();
      }
      editor.selection.setSelectionRange(range);
    } else {
      /* may be first run, set the editor to the code string
         re-generated by the sequencer, for better whitespace matching. */
      let regeneratedCode = SequencerStore.getEditorOutput().execCodeString;
      if (regeneratedCode && regeneratedCode !== editor.getValue()) {
        editor.setValue(regeneratedCode);
      }
    }
  }

  onPlayPauseUpdate = () => {
    // don't wait for the sequencer, it doesn't update
    // needlessly if only advancing a single step.
    // and even if it did, if the delay is set to high
    // we would still want to
    // give the user control again immediately.
    let editor = this.refs.aceEditor.editor;
    if (!LiveOptionStore.isCodeRunning()) {
      // we have finished, need to allow editing again
      editor.setReadOnly(false);
    }
  }

  onChangeCodeInEditor = () => {
    /* The Sequencer always checks the CodeStore preferentially to 
       the OptionStore for user-modified code that has overwritten
       the selectedExample.*/
    if (this.refs && this.refs.aceEditor) {
      let editor = this.refs.aceEditor.editor;
      // don't trigger change for programmatic events (adding IIFE info)
      // as this will clear the state of the DynamicControlBar
      if (editor.curOp && editor.curOp.command.name) {
        CodeStore.set(this.refs.aceEditor.editor.getValue());
      }
    }
  }


  render = () => {
    let {...other
    } = this.props.options;
    return (
      <div>
        <AceEditor ref="aceEditor"
        value = {this.props.staticCodeExample.toString()}
        onChange={this.onChangeCodeInEditor}
        {...other}/>
      </div>
    );
  }

}


export default Editor;
